import java.lang.instrument.Instrumentation;
import java.lang.reflect.*;
import java.nio.file.*;
import java.util.*;
import javax.xml.bind.JAXBContext;
import com.sun.tools.attach.VirtualMachine;
import com.aionemu.gameserver.dataholders.*;
import com.aionemu.gameserver.model.*;
import com.aionemu.gameserver.model.account.*;
import com.aionemu.gameserver.model.gameobjects.*;
import com.aionemu.gameserver.model.gameobjects.player.*;
import com.aionemu.gameserver.model.items.storage.*;
import com.aionemu.gameserver.model.team.*;
import com.aionemu.gameserver.model.team.group.*;
import com.aionemu.gameserver.services.player.PlayerService;
import com.aionemu.gameserver.services.playerbot.*;
import com.aionemu.gameserver.skillengine.model.*;
import com.aionemu.gameserver.skillengine.effect.AbnormalState;
import com.aionemu.gameserver.instance.handlers.GeneralInstanceHandler;
import com.aionemu.gameserver.world.*;
import com.aionemu.gameserver.utils.idfactory.IDFactory;

/** Actual installed defensive actions on isolated, unsaved native actors; no DB/human writes. */
public class PlayerBotDefenseCheckAgent3 {
 static void set(Object o,String name,Object value)throws Exception {for(Class<?> c=o.getClass();c!=null;c=c.getSuperclass())try{var f=c.getDeclaredField(name);f.setAccessible(true);f.set(o,value);return;}catch(NoSuchFieldException e){}throw new NoSuchFieldException(name);}
 static Player make(PlayerClass pc)throws Exception {int id=IDFactory.getInstance().nextId();var common=new PlayerCommonData(id);common.setName("DefenseFixture"+id);common.setRace(Race.ELYOS);common.setGender(Gender.FEMALE);common.setPlayerClass(pc);common.setDaeva(true);common.setLevel(20);var data=new PlayerAccountData(common,new PlayerAppearance());var account=new Account(2000000000);account.setName("DefenseFixture");account.addPlayerAccountData(data);account.setAccountWarehouse(new PlayerStorage(null,StorageType.ACCOUNT_WAREHOUSE));var p=PlayerService.newPlayer(data,account);p.setPlayerBotOwner(Integer.MAX_VALUE);PlayerBotGenerationOptions.initialize(p);p.setMotions(new com.aionemu.gameserver.model.gameobjects.player.motion.MotionList(p));return p;}
 static PlayerBotSkills.Entry entry(Player player,SkillTemplate skill){float range=skill.getProperties().getFirstTargetRange();if(skill.getProperties().isAddWeaponRange())range+=player.getGameStats().getAttackRange().getCurrent()/1000f;return new PlayerBotSkills.Entry(skill,skill.getLvl(),PlayerBotSkills.classify(skill),Math.max(1,range));}
 static void learn(Player player,int... ids)throws Exception {var f=com.aionemu.gameserver.model.skill.PlayerSkillList.class.getDeclaredField("skills");f.setAccessible(true);var learned=(Map<Integer,com.aionemu.gameserver.model.skill.PlayerSkillEntry>)f.get(player.getSkillList());for(int id:ids)learned.put(id,new com.aionemu.gameserver.model.skill.PlayerSkillEntry(id,DataManager.SKILL_DATA.getSkillTemplate(id).getLvl(),0,Persistable.PersistentState.NEW));}
 static void waitFor(java.util.function.BooleanSupplier finished,String why)throws Exception {long until=System.currentTimeMillis()+10000;while(!finished.getAsBoolean() && System.currentTimeMillis()<until)Thread.sleep(50);if(!finished.getAsBoolean())throw new AssertionError(why);}
 static String fingerprint(Player p){return p.getPlayerClass()+":"+p.getLevel()+":"+p.getAllItems().stream().sorted(Comparator.comparingInt(Item::getObjectId)).map(i->i.getObjectId()+"/"+i.getItemId()+"/"+i.getEquipmentSlot()+"/"+i.isEquipped()).toList()+":"+p.getSkillList().getAllSkills().stream().sorted(Comparator.comparingInt(com.aionemu.gameserver.model.skill.PlayerSkillEntry::getSkillId)).map(s->s.getSkillId()+"/"+s.getSkillLevel()).toList();}
 public static void agentmain(String argument,Instrumentation ignored)throws Exception {
  List<String> lines=new ArrayList<>();List<Player> players=new ArrayList<>();List<Npc> mobs=new ArrayList<>();List<PlayerBotSession> sessions=new ArrayList<>();List<PlayerBotLease> leases=new ArrayList<>();WorldMapInstance instance=null;PlayerGroup group=null;Map<Integer,PlayerBotSession> registered=null;
  synchronized(PlayerBotService.getInstance()){try {
   var world=World.getInstance();var map=world.getWorldMap(300040000);instance=WorldMapInstanceFactory.createWorldMapInstance(map,0,GeneralInstanceHandler::new,6);
   for(var pc:List.of(PlayerClass.SORCERER,PlayerClass.CLERIC,PlayerClass.RANGER,PlayerClass.ASSASSIN)){var p=make(pc);players.add(p);world.setPosition(p,map.getMapId(),instance.getInstanceId(),500+players.size()*.2f,500,100,(byte)0);world.storeObject(p);world.spawn(p);}
   var mage=players.get(0);var owner=players.get(1);var ranger=players.get(2);var rogue=players.get(3);for(var p:List.of(mage,ranger,rogue))set(p,"playerBotOwnerId",owner.getObjectId());
   owner.getCommonData().setOnline(true);var uf=sun.misc.Unsafe.class.getDeclaredField("theUnsafe");uf.setAccessible(true);var unsafe=(sun.misc.Unsafe)uf.get(null);var sink=(com.aionemu.gameserver.network.aion.AionConnection)unsafe.allocateInstance(com.aionemu.gameserver.network.aion.AionConnection.class);set(sink,"guard",new Object());set(sink,"closed",true);owner.setClientConnection(sink);
   group=new PlayerGroup(new PlayerGroupMember(owner),TeamType.GROUP,0);for(var p:players)group.addMember(new PlayerGroupMember(p));
   var template=DataManager.NPC_DATA.getNpcTemplate(210063);
   for(int i=0;i<4;i++) {
    var spawn=new com.aionemu.gameserver.model.templates.spawns.SpawnTemplate(new com.aionemu.gameserver.model.templates.spawns.SpawnGroup(map.getMapId(),template.getTemplateId(),0,null),501+i*.15f,500,100,(byte)0,0,null,0,0,com.aionemu.gameserver.model.templates.spawns.SpawnTemplate.NO_AI);
    var npc=new Npc(new com.aionemu.gameserver.controllers.NpcController(){@Override public void onAddHate(Creature c,boolean first){}},spawn,template);set(npc,"ai",new com.aionemu.gameserver.ai.NpcAI(npc){@Override protected void handleSpawned(){} @Override protected void handleTargetChanged(Creature c){} });mobs.add(npc);npc.setKnownlist(new com.aionemu.gameserver.world.knownlist.NpcKnownList(npc));npc.setEffectController(new com.aionemu.gameserver.controllers.effect.EffectController(npc));world.setPosition(npc,map.getMapId(),instance.getInstanceId(),spawn.getX(),500,100,(byte)0);world.storeObject(npc);world.spawn(npc);
    npc.getGameStats().addEffect(new com.aionemu.gameserver.model.stats.calc.StatOwner(){},List.of(new com.aionemu.gameserver.model.stats.calc.functions.StatAddFunction(com.aionemu.gameserver.model.stats.container.StatEnum.MAXHP,10000,false)));npc.getLifeStats().synchronizeWithMaxStats();npc.setTarget(owner);if(i<3)npc.getAggroList().addHate(owner,100);
   }
   var pursuer=mobs.get(0);var rangedPursuer=mobs.get(1);var spellCaster=mobs.get(2);var idle=mobs.get(3);
   var ctor=PlayerBotSession.class.getDeclaredConstructor(Player.class,Player.class,PlayerBotLease.class,int.class,boolean.class);ctor.setAccessible(true);var field=PlayerBotService.class.getDeclaredField("sessions");field.setAccessible(true);registered=(Map<Integer,PlayerBotSession>)field.get(PlayerBotService.getInstance());
   for(var p:List.of(mage,ranger,rogue)){var lease=PlayerBotLease.acquire(p.getObjectId());leases.add(lease);var s=ctor.newInstance(owner,p,lease,0,false);sessions.add(s);if(registered.putIfAbsent(p.getObjectId(),s)!=null)throw new AssertionError("Fixture session collision");}
   var mageSession=sessions.get(0);var rangerSession=sessions.get(1);var rogueSession=sessions.get(2);learn(mage,1155,1328);learn(ranger,950);learn(rogue,3272);
   var bowTemplate=DataManager.ITEM_DATA.getItemTemplates().stream().filter(t->t.isWeapon() && t.getItemGroup()==com.aionemu.gameserver.model.templates.item.enums.ItemGroup.BOW && t.getLevel()>0 && t.getLevel()<=ranger.getLevel()).min(Comparator.comparingInt(com.aionemu.gameserver.model.templates.item.ItemTemplate::getLevel).thenComparingInt(com.aionemu.gameserver.model.templates.item.ItemTemplate::getTemplateId)).orElseThrow();lines.add("FIXTURE_BOW: "+bowTemplate.getTemplateId()+" "+bowTemplate.getName());var bow=com.aionemu.gameserver.services.item.ItemFactory.newItem(bowTemplate.getTemplateId());ranger.getInventory().add(bow);if(ranger.getEquipment().equipItem(bow.getObjectId(),com.aionemu.gameserver.model.items.ItemSlot.MAIN_HAND.getSlotIdMask())==null)throw new AssertionError("Native fixture bow equip rejected");
   var before=players.stream().map(PlayerBotDefenseCheckAgent3::fingerprint).toList();
   var data=(SkillData)JAXBContext.newInstance(SkillData.class).createUnmarshaller().unmarshal(new java.io.StringReader("""
    <skill_data>
     <skill_template skill_id="990311" name="hostile damage fixture" lvl="1" activation="PROVOKED" skilltype="MAGICAL"><properties first_target="TARGET" target_relation="ENEMY" target_type="ONLYONE" first_target_range="25"/><effects><spellatkinstant value="100" e="1" noresist="true" hoptype="DAMAGE"/></effects></skill_template>
     <skill_template skill_id="990312" name="hostile casting fixture" lvl="1" activation="PROVOKED" skilltype="MAGICAL" duration="12000"><properties first_target="TARGET" target_relation="ENEMY" target_type="ONLYONE" first_target_range="25"/><effects><spellatkinstant value="100" e="1" noresist="true" hoptype="DAMAGE"/></effects></skill_template>
     <skill_template skill_id="990313" name="existing protection fixture" lvl="1" activation="PROVOKED" skilltype="MAGICAL" tslot="BUFF" stack="DEFENSE_FIXTURE"><properties first_target="ME" target_relation="FRIEND" target_type="ONLYONE"/><effects><shield hitvalue="2000" value="2000" e="1" duration2="30000" effectid="154" noresist="true"/></effects></skill_template>
    </skill_data>
    """));
   var recipient=PlayerBotSession.class.getDeclaredMethod("recipient",PlayerBotSkills.Entry.class,List.class,Npc.class,boolean.class);recipient.setAccessible(true);var priority=PlayerBotSession.class.getDeclaredMethod("priority",PlayerBotSkills.Entry.class,Creature.class,boolean.class,List.class);priority.setAccessible(true);
   var skin=entry(mage,DataManager.SKILL_DATA.getSkillTemplate(1155));var root=entry(mage,DataManager.SKILL_DATA.getSkillTemplate(1328));var shot=entry(ranger,DataManager.SKILL_DATA.getSkillTemplate(950));var resist=entry(rogue,DataManager.SKILL_DATA.getSkillTemplate(3272));
   if(recipient.invoke(mageSession,skin,players,pursuer,true)!=null)throw new AssertionError("Healthy unpressured Mage wastes barrier");mage.getLifeStats().setCurrentHpPercent(64);int hp=mage.getLifeStats().getCurrentHp(),mp=mage.getLifeStats().getCurrentMp();for(int i=0;i<100;i++)if(recipient.invoke(mageSession,skin,players,pursuer,true)!=mage || (double)priority.invoke(mageSession,skin,mage,true,players)!=29)throw new AssertionError("Native medium-health barrier missing or wrong band");if(mage.getLifeStats().getCurrentHp()!=hp || mage.getLifeStats().getCurrentMp()!=mp)throw new AssertionError("Defensive planning changes resources");mage.getLifeStats().setCurrentHpPercent(100);pursuer.setTarget(mage);if(recipient.invoke(mageSession,skin,players,pursuer,true)!=mage)throw new AssertionError("Healthy pressured Mage does not shield");lines.add("OK: installed healthy/pressured/medium-health shield decisions use band 29 before panic, with no planning resource changes.");
   var existing=new Effect(mage,mage,data.getSkillTemplate(990313),1,30000,null);existing.initialize();existing.applyEffect();mage.getLifeStats().setCurrentHpPercent(20);if(recipient.invoke(mageSession,skin,players,pursuer,true)!=null)throw new AssertionError("Existing native shield overwritten");existing.endEffect();mage.getLifeStats().setCurrentHpPercent(100);lines.add("OK: native effect-slot/capacity conflict preserves existing protection even during panic.");
   var actionType=Class.forName("com.aionemu.gameserver.services.playerbot.PlayerBotSession$CastAction");var actionCtor=actionType.getDeclaredConstructor(PlayerBotSession.class,PlayerBotSkills.Entry.class,Creature.class,List.class);actionCtor.setAccessible(true);var execute=actionType.getDeclaredMethod("execute");execute.setAccessible(true);var useful=actionType.getDeclaredMethod("isUseful");useful.setAccessible(true);
   int baseline=mage.getLifeStats().getCurrentHp();var hit=new Skill(data.getSkillTemplate(990311),pursuer,1,mage,null);if(!hit.useSkill())throw new AssertionError("Native damage fixture rejected");waitFor(()->mage.getLifeStats().getCurrentHp()<baseline,"Unprotected native hit did no damage");int baselineDamage=baseline-mage.getLifeStats().getCurrentHp();mage.getLifeStats().setCurrentHpPercent(100);int manaBefore=mage.getLifeStats().getCurrentMp();Object shielding=actionCtor.newInstance(mageSession,skin,mage,mobs.subList(0,3));if(!(boolean)execute.invoke(shielding))throw new AssertionError("Installed Stone Skin action rejected");waitFor(()->mage.getEffectController().hasAbnormalEffect(e->e.getSkillId()==1155),"Native Stone Skin did not apply");if(mage.getLifeStats().getCurrentMp()>=manaBefore || (boolean)useful.invoke(shielding))throw new AssertionError("Native shield MP or duplicate guard failed");int protectedHp=mage.getLifeStats().getCurrentHp();if(!new Skill(data.getSkillTemplate(990311),pursuer,1,mage,null).useSkill())throw new AssertionError("Protected native damage fixture rejected");Thread.sleep(500);if(mage.getLifeStats().getCurrentHp()!=protectedHp)throw new AssertionError("Actual native Stone Skin did not absorb the hit");lines.add("OK: actual installed Stone Skin paid MP, rejected a duplicate and absorbed a native hit that dealt "+baselineDamage+" HP without protection.");mage.getEffectController().removeEffect(1155);
   if(recipient.invoke(mageSession,root,players,spellCaster,true)!=pursuer || (double)priority.invoke(mageSession,root,pursuer,true,players)!=50)throw new AssertionError("Close secondary pursuer did not receive Mage peel");set(mageSession,"role",PlayerBotRules.Role.TANK);if((double)priority.invoke(mageSession,root,pursuer,true,players)!=0)throw new AssertionError("Assigned tank roots/kites its own enemy");set(mageSession,"role",PlayerBotRules.Role.RANGED);pursuer.setTarget(owner);pursuer.setCasting(new Skill(data.getSkillTemplate(990312),pursuer,1,owner,null));if((double)priority.invoke(mageSession,root,pursuer,true,players)!=0)throw new AssertionError("Root falsely treated as spell interrupt");pursuer.setCasting(null);pursuer.setTarget(mage);
   idle.setTarget(mage);spellCaster.setTarget(owner);if(recipient.invoke(mageSession,root,players,spellCaster,true)!=pursuer)throw new AssertionError("Unengaged close NPC admitted to defensive pull set");Object rooting=actionCtor.newInstance(mageSession,root,pursuer,mobs.subList(0,3));if(!(boolean)execute.invoke(rooting))throw new AssertionError("Actual Root action rejected");if(!PlayerBotService.getInstance().isReserved(ranger,pursuer,PlayerBotRules.SkillKind.CONTROL))throw new AssertionError("Peel cast did not reserve crowd control");waitFor(()->pursuer.getEffectController().isAbnormalSet(AbnormalState.ROOT),"Actual native Root did not immobilize pursuer");if((boolean)useful.invoke(rooting))throw new AssertionError("Already rooted enemy keeps receiving a root");lines.add("OK: installed Root immobilized a close secondary pursuer and reserved control; tank role, non-pursuing caster, already-rooted and unengaged NPC cases do not trigger it.");
   rangedPursuer.setTarget(ranger);if(recipient.invoke(rangerSession,shot,players,spellCaster,true)!=rangedPursuer || (double)priority.invoke(rangerSession,shot,rangedPursuer,true,players)<20)throw new AssertionError("Native bow snare did not select Ranger pursuer");Object snaring=actionCtor.newInstance(rangerSession,shot,rangedPursuer,mobs.subList(0,3));int shotMp=ranger.getLifeStats().getCurrentMp();if(!(boolean)execute.invoke(snaring))throw new AssertionError("Actual Entangling Shot rejected");if(!PlayerBotService.getInstance().isReserved(mage,rangedPursuer,PlayerBotRules.SkillKind.CONTROL))throw new AssertionError("Damaging snare did not reserve control");waitFor(()->rangedPursuer.getEffectController().isAbnormalSet(AbnormalState.SNARE),"Native Entangling Shot did not snare");if(ranger.getLifeStats().getCurrentMp()>=shotMp)throw new AssertionError("Native snare did not pay MP");var defense=Class.forName("com.aionemu.gameserver.services.playerbot.PlayerBotDefense");var peel=defense.getDeclaredMethod("peelPriority",Player.class,PlayerBotRules.Role.class,PlayerBotSkills.Entry.class,Creature.class);peel.setAccessible(true);if((double)peel.invoke(null,ranger,PlayerBotRules.Role.RANGED,shot,rangedPursuer)!=0)throw new AssertionError("Existing snare still has defensive relevance");lines.add("OK: actual bow-based Entangling Shot snared its pursuer, paid MP and reserved control without repeated defensive snaring.");
   rogue.getLifeStats().setCurrentHpPercent(24);spellCaster.setTarget(rogue);if(recipient.invoke(rogueSession,resist,players,spellCaster,true)!=null)throw new AssertionError("Magic resistance wasted on melee-only pressure");spellCaster.setCasting(new Skill(data.getSkillTemplate(990312),spellCaster,1,rogue,null));if(recipient.invoke(rogueSession,resist,players,spellCaster,true)!=rogue || (double)priority.invoke(rogueSession,resist,rogue,true,players)!=27)throw new AssertionError("Native incoming magic protection missing or wrong class band");Object resisting=actionCtor.newInstance(rogueSession,resist,rogue,mobs.subList(0,3));if(!(boolean)execute.invoke(resisting))throw new AssertionError("Actual Spelldodging action rejected");waitFor(()->rogue.getEffectController().hasAbnormalEffect(e->e.getSkillId()==3272),"Actual Spelldodging did not apply");spellCaster.setCasting(null);lines.add("OK: native Spelldodging protects against an incoming hostile magical cast at the original critical-health band, without wasting charges on melee pressure.");
   if(!before.equals(players.stream().map(PlayerBotDefenseCheckAgent3::fingerprint).toList()))throw new AssertionError("Owned-alt fixture class/level/equipment/skills changed");lines.add("OK: owned-alt fixture class/level/equipment/skills fingerprints are unchanged by planning and combat decisions.");
   lines.add("SUCCESS: installed proactive defenses, native shield absorption, root/snare casts and reservations, magical resistance, role/target/stack safety and planning purity. No database/human-character writes.");
  }catch(Throwable error){var trace=new java.io.StringWriter();error.printStackTrace(new java.io.PrintWriter(trace));lines.add("FAIL: "+trace);}
  finally {
   if(registered!=null)for(var s:sessions)registered.remove(s.bot().getObjectId(),s);
   for(var s:sessions){var close=Class.forName("com.aionemu.gameserver.services.playerbot.PlayerBotQuestSync").getDeclaredMethod("close",PlayerBotSession.class);close.setAccessible(true);close.invoke(null,s);}for(var lease:leases)lease.close();
   for(var npc:mobs){npc.getController().cancelCurrentSkill(null);npc.getEffectController().removeAllEffects(true);npc.getLifeStats().cancelAllTasks();npc.getAggroList().clear();if(npc.isSpawned())World.getInstance().despawn(npc);World.getInstance().removeObject(npc);}
   if(group!=null)for(var p:players){group.removeMember(p.getObjectId());p.setPlayerGroup(null);}
   for(var p:players){p.getController().cancelCurrentSkill(null);p.getLifeStats().cancelAllTasks();p.getEffectController().removeAllEffects(true);if(p.isSpawned())World.getInstance().despawn(p);World.getInstance().removeObject(p);for(var item:p.getAllItems())IDFactory.getInstance().releaseId(item.getObjectId());IDFactory.getInstance().releaseId(p.getObjectId());Files.deleteIfExists(Path.of("config/playerbots/character-"+p.getObjectId()+".properties"));}
   if(instance!=null)World.getInstance().getWorldMap(instance.getMapId()).removeWorldMapInstance(instance.getInstanceId());
  }}
  Files.write(Path.of(argument),lines,StandardOpenOption.CREATE_NEW);if(lines.stream().anyMatch(s->s.startsWith("FAIL:")))throw new AssertionError("Native defense check failed; diagnostic saved");
 }
 public static void main(String[] args)throws Exception{var vm=VirtualMachine.attach(args[0]);try{vm.loadAgent(Path.of(args[1]).toAbsolutePath().toString(),Path.of(args[2]).toAbsolutePath().toString());}finally{vm.detach();}}
}

