import java.lang.instrument.Instrumentation;
import java.lang.reflect.*;
import java.nio.file.*;
import java.util.*;
import javax.xml.bind.JAXBContext;
import com.sun.tools.attach.VirtualMachine;
import com.aionemu.gameserver.dataholders.*;
import com.aionemu.gameserver.model.*;
import com.aionemu.gameserver.model.account.*;
import com.aionemu.gameserver.model.gameobjects.*;
import com.aionemu.gameserver.model.gameobjects.player.*;
import com.aionemu.gameserver.model.items.storage.*;
import com.aionemu.gameserver.model.team.group.*;
import com.aionemu.gameserver.model.team.TeamType;
import com.aionemu.gameserver.services.player.PlayerService;
import com.aionemu.gameserver.services.playerbot.*;
import com.aionemu.gameserver.skillengine.model.*;
import com.aionemu.gameserver.instance.handlers.GeneralInstanceHandler;
import com.aionemu.gameserver.world.*;
import com.aionemu.gameserver.utils.idfactory.IDFactory;

/** Native installed actions on private, unsaved fixture actors. No database writes. */
public class PlayerBotEnemyUtilityCheckAgent4 {
 static void set(Object o,String name,Object value)throws Exception {for(Class<?> c=o.getClass();c!=null;c=c.getSuperclass())try{var f=c.getDeclaredField(name);f.setAccessible(true);f.set(o,value);return;}catch(NoSuchFieldException e){}throw new NoSuchFieldException(name);}
 static Player make(PlayerClass pc)throws Exception {int id=IDFactory.getInstance().nextId();var common=new PlayerCommonData(id);common.setName("UtilityFixture"+id);common.setRace(Race.ELYOS);common.setGender(Gender.FEMALE);common.setPlayerClass(pc);common.setDaeva(true);common.setLevel(20);var data=new PlayerAccountData(common,new PlayerAppearance());var account=new Account(2000000000);account.setName("UtilityFixture");account.addPlayerAccountData(data);account.setAccountWarehouse(new PlayerStorage(null,StorageType.ACCOUNT_WAREHOUSE));var p=PlayerService.newPlayer(data,account);p.setPlayerBotOwner(Integer.MAX_VALUE);PlayerBotGenerationOptions.initialize(p);p.setMotions(new com.aionemu.gameserver.model.gameobjects.player.motion.MotionList(p));return p;}
 static PlayerBotSkills.Entry entry(SkillTemplate skill){return new PlayerBotSkills.Entry(skill,skill.getLvl(),PlayerBotSkills.classify(skill),Math.max(1,skill.getProperties().getFirstTargetRange()));}
 static Effect add(Npc npc,SkillTemplate template)throws Exception {var effect=new Effect(npc,npc,template,1,30000,null);effect.initialize();effect.applyEffect();if(!npc.getEffectController().hasAbnormalEffect(e->e==effect))throw new AssertionError("Native fixture buff was not applied: "+template.getSkillId());return effect;}
 static void await(Player p)throws Exception {long until=System.currentTimeMillis()+10000;while(p.isCasting() && System.currentTimeMillis()<until)Thread.sleep(50);Thread.sleep(1500);}
 public static void agentmain(String argument,Instrumentation ignored)throws Exception {
  List<String> lines=new ArrayList<>();List<Player> players=new ArrayList<>();List<Npc> mobs=new ArrayList<>();WorldMapInstance instance=null;PlayerGroup group=null;PlayerBotSession session=null;PlayerBotLease lease=null;Map<Integer,PlayerBotSession> registered=null;
  synchronized(PlayerBotService.getInstance()){try {
   var world=World.getInstance();var map=world.getWorldMap(300040000);instance=WorldMapInstanceFactory.createWorldMapInstance(map,0,GeneralInstanceHandler::new,6);
   for(var pc:List.of(PlayerClass.SPIRIT_MASTER,PlayerClass.CLERIC,PlayerClass.TEMPLAR)){var p=make(pc);players.add(p);world.setPosition(p,map.getMapId(),instance.getInstanceId(),500+players.size()*.2f,500,100,(byte)0);world.storeObject(p);world.spawn(p);}
   var bot=players.get(0);var owner=players.get(1);var tank=players.get(2);set(bot,"playerBotOwnerId",owner.getObjectId());set(tank,"playerBotOwnerId",owner.getObjectId());
   owner.getCommonData().setOnline(true);var uf=sun.misc.Unsafe.class.getDeclaredField("theUnsafe");uf.setAccessible(true);var unsafe=(sun.misc.Unsafe)uf.get(null);var sink=(com.aionemu.gameserver.network.aion.AionConnection)unsafe.allocateInstance(com.aionemu.gameserver.network.aion.AionConnection.class);set(sink,"guard",new Object());set(sink,"closed",true);owner.setClientConnection(sink);
   group=new PlayerGroup(new PlayerGroupMember(owner),TeamType.GROUP,0);for(var p:players)group.addMember(new PlayerGroupMember(p));
   var template=DataManager.NPC_DATA.getNpcTemplate(210063);
   for(int i=0;i<3;i++) {
    var spawn=new com.aionemu.gameserver.model.templates.spawns.SpawnTemplate(new com.aionemu.gameserver.model.templates.spawns.SpawnGroup(map.getMapId(),template.getTemplateId(),0,null),500.8f+i*.2f,500,100,(byte)0,0,null,0,0,com.aionemu.gameserver.model.templates.spawns.SpawnTemplate.NO_AI);
    var npc=new Npc(new com.aionemu.gameserver.controllers.NpcController(){@Override public void onAddHate(Creature c,boolean first){}},spawn,template);mobs.add(npc);npc.setKnownlist(new com.aionemu.gameserver.world.knownlist.NpcKnownList(npc));npc.setEffectController(new com.aionemu.gameserver.controllers.effect.EffectController(npc));world.setPosition(npc,map.getMapId(),instance.getInstanceId(),spawn.getX(),500,100,(byte)0);world.storeObject(npc);world.spawn(npc);
    npc.getGameStats().addEffect(new com.aionemu.gameserver.model.stats.calc.StatOwner(){},List.of(new com.aionemu.gameserver.model.stats.calc.functions.StatAddFunction(com.aionemu.gameserver.model.stats.container.StatEnum.MAXHP,10000,false)));npc.getLifeStats().synchronizeWithMaxStats();npc.setTarget(tank);
   }
   var primary=mobs.get(0);var caster=mobs.get(1);var idle=mobs.get(2);primary.getAggroList().addHate(tank,100);caster.getAggroList().addHate(tank,100);
   var ctor=PlayerBotSession.class.getDeclaredConstructor(Player.class,Player.class,PlayerBotLease.class,int.class,boolean.class);ctor.setAccessible(true);lease=PlayerBotLease.acquire(bot.getObjectId());session=ctor.newInstance(owner,bot,lease,0,false);var sessions=PlayerBotService.class.getDeclaredField("sessions");sessions.setAccessible(true);registered=(Map<Integer,PlayerBotSession>)sessions.get(PlayerBotService.getInstance());if(registered.putIfAbsent(bot.getObjectId(),session)!=null)throw new AssertionError("Fixture id already registered");
   if(!PlayerBotService.allowsTarget(bot,primary) || !bot.getKnownList().sees(caster))throw new AssertionError("Native party/engagement fixture invalid");
   var learnedField=com.aionemu.gameserver.model.skill.PlayerSkillList.class.getDeclaredField("skills");learnedField.setAccessible(true);var learned=(Map<Integer,com.aionemu.gameserver.model.skill.PlayerSkillEntry>)learnedField.get(bot.getSkillList());for(int id:new int[]{305,3532,3740,3572})learned.put(id,new com.aionemu.gameserver.model.skill.PlayerSkillEntry(id,DataManager.SKILL_DATA.getSkillTemplate(id).getLvl(),0,com.aionemu.gameserver.model.gameobjects.Persistable.PersistentState.NEW));
   var data=(SkillData)JAXBContext.newInstance(SkillData.class).createUnmarshaller().unmarshal(new java.io.StringReader("""
    <skill_data>
     <skill_template skill_id="990211" name="removable attack boost" lvl="1" activation="PROVOKED" skilltype="MAGICAL" tslot="BUFF" stack="UTILITY_FIXTURE" dispel_category="BUFF" req_dispel_level="1" req_dispel_count="10"><effects><statup e="1" noresist="true" duration2="30000"><change stat="PHYSICAL_ATTACK" func="PERCENT" value="10"/></statup></effects></skill_template>
     <skill_template skill_id="990212" name="strong protection" lvl="1" activation="PROVOKED" skilltype="MAGICAL" tslot="BUFF" stack="UTILITY_STRONG_FIXTURE" dispel_category="BUFF" req_dispel_level="1" req_dispel_count="50"><effects><shield value="1000" value2="100" e="1" noresist="true" duration2="30000"/></effects></skill_template>
     <skill_template skill_id="990213" name="higher level protection" lvl="1" activation="PROVOKED" skilltype="MAGICAL" tslot="BUFF" stack="UTILITY_LEVEL_FIXTURE" dispel_category="BUFF" req_dispel_level="2" req_dispel_count="10"><effects><shield value="1000" value2="100" e="1" noresist="true" duration2="30000"/></effects></skill_template>
     <skill_template skill_id="990214" name="npc only protection" lvl="1" activation="PROVOKED" skilltype="MAGICAL" tslot="BUFF" stack="UTILITY_NPC_FIXTURE" dispel_category="NPC_BUFF" req_dispel_level="3" req_dispel_count="10"><effects><shield value="1000" value2="100" e="1" noresist="true" duration2="30000"/></effects></skill_template>
     <skill_template skill_id="990215" name="fixture heal cast" lvl="1" activation="PROVOKED" skilltype="MAGICAL" duration="12000"><properties first_target="ME" target_relation="FRIEND" target_type="ONLYONE"/><effects><healinstant value="100" e="1" noresist="true"/></effects></skill_template>
     <skill_template skill_id="990216" name="fixture attack cast" lvl="1" activation="PROVOKED" skilltype="MAGICAL" duration="12000"><properties first_target="TARGET" target_relation="ENEMY" target_type="ONLYONE" first_target_range="25"/><effects><spellatkinstant value="100" e="1" noresist="true"/></effects></skill_template>
    </skill_data>
    """));
   var helper=Class.forName("com.aionemu.gameserver.services.playerbot.PlayerBotEnemyUtility");var score=helper.getDeclaredMethod("purgeScore",Creature.class,PlayerBotSkills.Entry.class,Creature.class);score.setAccessible(true);
   var recipient=PlayerBotSession.class.getDeclaredMethod("recipient",PlayerBotSkills.Entry.class,List.class,Npc.class,boolean.class);recipient.setAccessible(true);var priority=PlayerBotSession.class.getDeclaredMethod("priority",PlayerBotSkills.Entry.class,Creature.class,boolean.class,List.class);priority.setAccessible(true);
   var ignite=entry(DataManager.SKILL_DATA.getSkillTemplate(3532));var dispel=entry(DataManager.SKILL_DATA.getSkillTemplate(305));var breaker=entry(DataManager.SKILL_DATA.getSkillTemplate(3740));var silence=entry(DataManager.SKILL_DATA.getSkillTemplate(3572));
   if(recipient.invoke(session,ignite,players,primary,true)!=null)throw new AssertionError("Pure counter purge selected an empty target");
   var strong=add(primary,data.getSkillTemplate(990212));double partial=(double)score.invoke(null,bot,ignite,primary),full=(double)score.invoke(null,bot,breaker,primary);if(!(partial>0 && full>partial))throw new AssertionError("Partial native power progression or full-removal preference lost");int power=strong.getPower(),mp=bot.getLifeStats().getCurrentMp();for(int i=0;i<100;i++){score.invoke(null,bot,ignite,primary);recipient.invoke(session,ignite,players,primary,true);}if(strong.getPower()!=power || strong.getDesignatedDispelEffect()!=null || bot.getLifeStats().getCurrentMp()!=mp)throw new AssertionError("Planning consumed native effect power/resources");lines.add("OK: partial power contribution is useful; full removal ranks higher; repeated installed selection/score leaves power, designation and MP untouched.");
   strong.setDesignatedDispelEffect(new Effect(bot,primary,ignite.template(),1));if((double)score.invoke(null,bot,ignite,primary)!=0)throw new AssertionError("In-flight native dispel designation ignored");strong.resetDesignatedDispelEffect();strong.endEffect();
   var higher=add(primary,data.getSkillTemplate(990213));if((double)score.invoke(null,bot,ignite,primary)!=0)throw new AssertionError("Native required dispel level ignored");higher.endEffect();var npcOnly=add(primary,data.getSkillTemplate(990214));if((double)score.invoke(null,bot,ignite,primary)!=0)throw new AssertionError("Player purge erased native NPC_BUFF category");npcOnly.endEffect();lines.add("OK: native designation, dispel-level and NPC_BUFF exclusions survive the port.");
   var protection=add(primary,data.getSkillTemplate(990211));if(recipient.invoke(session,ignite,players,primary,true)!=primary || (double)priority.invoke(session,ignite,primary,true,players)<=50)throw new AssertionError("Installed class purge not prioritized above ordinary attacks");
   var actionType=Class.forName("com.aionemu.gameserver.services.playerbot.PlayerBotSession$CastAction");var actionCtor=actionType.getDeclaredConstructor(PlayerBotSession.class,PlayerBotSkills.Entry.class,Creature.class,List.class);actionCtor.setAccessible(true);var execute=actionType.getDeclaredMethod("execute");execute.setAccessible(true);var useful=actionType.getDeclaredMethod("isUseful");useful.setAccessible(true);
   int hp=primary.getLifeStats().getCurrentHp();mp=bot.getLifeStats().getCurrentMp();Object action=actionCtor.newInstance(session,ignite,primary,List.of(primary,caster));if(!(boolean)execute.invoke(action))throw new AssertionError("Actual native Ignite Aether cast rejected");await(bot);long impactDeadline=System.currentTimeMillis()+10000;while(primary.getEffectController().hasAbnormalEffect(e->e==protection) && System.currentTimeMillis()<impactDeadline)Thread.sleep(100);lines.add("COUNTER: allowed="+PlayerBotService.allowsTarget(bot,primary)+" power="+protection.getPower()+" designated="+(protection.getDesignatedDispelEffect()==null ? "none" : protection.getDesignatedDispelEffect().getSkill().getHitTime())+" buff="+primary.getEffectController().hasAbnormalEffect(e->e==protection)+" MP="+mp+"->"+bot.getLifeStats().getCurrentMp()+" HP="+hp+"->"+primary.getLifeStats().getCurrentHp());if(primary.getEffectController().hasAbnormalEffect(e->e==protection) || bot.getLifeStats().getCurrentMp()>=mp || primary.getLifeStats().getCurrentHp()>=hp)throw new AssertionError("Actual counter purge did not remove protection, pay MP and deal native counter damage");if((boolean)useful.invoke(action))throw new AssertionError("CastAction kept an empty pure purge useful after removal");lines.add("OK: actual installed Ignite Aether action removed native protection, paid MP, dealt counter damage and became useless on the now-empty target.");
   primary.setCasting(new Skill(data.getSkillTemplate(990216),primary,1,tank,null));caster.setCasting(new Skill(data.getSkillTemplate(990215),caster,1,caster,null));idle.setCasting(new Skill(data.getSkillTemplate(990215),idle,1,idle,null));
   if(recipient.invoke(session,silence,players,primary,true)!=primary)throw new AssertionError("Equal interrupt bands lost the stable primary target");primary.setCasting(null);if(recipient.invoke(session,silence,players,primary,true)!=caster)throw new AssertionError("Secondary engaged enemy healer not selected when primary is not casting");primary.setCasting(new Skill(data.getSkillTemplate(990216),primary,1,tank,null));var interruptScore=helper.getDeclaredMethod("interruptPriority",PlayerClass.class,Creature.class);interruptScore.setAccessible(true);if((double)interruptScore.invoke(null,PlayerClass.ASSASSIN,primary)!=42 || (double)interruptScore.invoke(null,PlayerClass.ASSASSIN,caster)!=41 || (double)interruptScore.invoke(null,PlayerClass.SORCERER,caster)!=40)throw new AssertionError("Pinned class interrupt bands changed");PlayerBotService.getInstance().reserve(tank,caster,PlayerBotRules.SkillKind.CONTROL,System.currentTimeMillis()+5000);if(recipient.invoke(session,silence,players,primary,true)!=primary)throw new AssertionError("Reserved interrupt did not select another actual party caster");
   primary.setCasting(null);caster.setCasting(null);idle.setCasting(null);PlayerBotService.getInstance().reserve(tank,caster,PlayerBotRules.SkillKind.CONTROL,System.currentTimeMillis()-1);lines.add("OK: installed interrupt selection retains the primary on ties, selects a reachable engaged healer otherwise, honors reservations, excludes unengaged NPCs and preserves the exact pinned Mage/Rogue interrupt bands.");
   caster.getLifeStats().setCurrentHpPercent(80);var healCast=new Skill(data.getSkillTemplate(990215),caster,1,caster,null);if(!healCast.useSkill() || !caster.isCasting())throw new AssertionError("Native enemy healing cast did not start");int before=bot.getLifeStats().getCurrentMp();Object interrupt=actionCtor.newInstance(session,silence,caster,List.of(primary,caster));if(!(boolean)execute.invoke(interrupt))throw new AssertionError("Actual native Sigil of Silence cast rejected");await(bot);if(caster.isCasting() || !caster.getEffectController().isAbnormalSet(com.aionemu.gameserver.skillengine.effect.AbnormalState.SILENCE) || bot.getLifeStats().getCurrentMp()>=before)throw new AssertionError("Native silence did not cancel an enemy healing cast and pay MP");lines.add("OK: actual installed Sigil of Silence cancelled a native enemy healing cast, applied silence and paid MP.");
   lines.add("SUCCESS: installed native purge/interrupt behavior, class priority, planning purity, eligible party-only secondary targets and reservation fallback. No database or human-character changes.");
  }catch(Throwable error){var trace=new java.io.StringWriter();error.printStackTrace(new java.io.PrintWriter(trace));lines.add("FAIL: "+trace);}
  finally {
   if(session!=null && registered!=null)registered.remove(session.bot().getObjectId(),session);
   if(session!=null){var close=Class.forName("com.aionemu.gameserver.services.playerbot.PlayerBotQuestSync").getDeclaredMethod("close",PlayerBotSession.class);close.setAccessible(true);close.invoke(null,session);}if(lease!=null)lease.close();
   for(var npc:mobs){npc.getController().cancelCurrentSkill(null);npc.getEffectController().removeAllEffects(true);npc.getLifeStats().cancelAllTasks();npc.getAggroList().clear();if(npc.isSpawned())World.getInstance().despawn(npc);World.getInstance().removeObject(npc);}
   if(group!=null)for(var p:players){group.removeMember(p.getObjectId());p.setPlayerGroup(null);}
   for(var p:players){p.getController().cancelCurrentSkill(null);p.getLifeStats().cancelAllTasks();p.getEffectController().removeAllEffects(true);if(p.isSpawned())World.getInstance().despawn(p);World.getInstance().removeObject(p);for(var item:p.getAllItems())IDFactory.getInstance().releaseId(item.getObjectId());IDFactory.getInstance().releaseId(p.getObjectId());Files.deleteIfExists(Path.of("config/playerbots/character-"+p.getObjectId()+".properties"));}
   if(instance!=null)World.getInstance().getWorldMap(instance.getMapId()).removeWorldMapInstance(instance.getInstanceId());
  }}
  Files.write(Path.of(argument),lines,StandardOpenOption.CREATE_NEW);if(lines.stream().anyMatch(s->s.startsWith("FAIL:")))throw new AssertionError("Native enemy utility failed; diagnostic saved");
 }
 public static void main(String[] args)throws Exception{var vm=VirtualMachine.attach(args[0]);try{vm.loadAgent(Path.of(args[1]).toAbsolutePath().toString(),Path.of(args[2]).toAbsolutePath().toString());}finally{vm.detach();}}
}

