#
# ----------------------------
# Drop config's:
# ----------------------------

# Announce when a player drops an item with the given minimum item quality (or higher). Leave empty to disable drop announces
# Possible values: JUNK, COMMON, RARE, LEGEND, UNIQUE, EPIC or MYTHIC
# Default: MYTHIC
gameserver.drop.announce_quality = MYTHIC

# Comma separated list of map ids where team members can roll for drops anywhere on the map instead of in the default range
# Default:
gameserver.drop.disable_range_check_maps =

# Number of quest items in each successful mob quest drop. This does not change the drop chance.
# Values below 1 are treated as 1. Default: 1
gameserver.drop.quest_item_count = 3
